(function(_ds){var window=this;var oT=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.Uk(a,nT(),b)},nT=_ds.oh(function(){return _ds.le&&9==_ds.Ge?"-ms-transform":"transform"});var rT=function(a){a.j=pT(a,".devsite-top-logo-row-wrapper-wrapper");a.h=pT(a,".devsite-collapsible-section");a.v=pT(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);qT(a)},qT=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(_ds.Uk(b,"transform",`translate3d(0, -${a.offset}px, 0)`),sT(a),a.G=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},tT=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.I(a.H);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.Bh(b.offsetWidth,b.offsetHeight);b=new _ds.Bh(c.offsetWidth,c.offsetHeight);var f=_ds.ml(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Uk(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});oT(c,a.hasAttribute("search-active")?0:e);_ds.Ok(a.H,d,_ds.wf,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),oT(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.Uk(d,nT(),m);oT(c,k)})}},uT=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.xj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},wT=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Z;_ds.vi(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>vT(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{vT(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},xT=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},sT=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},vT=function(a){window.requestAnimationFrame(()=>
a.K.h())},pT=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},yT=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},zT=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.fh(a,c,b))},AT=class extends _ds.E{constructor(){super(...arguments);this.eventHandler=new _ds.H;this.G=
-1;this.H=new _ds.H;this.D=0;this.F=new MutationObserver(()=>rT(this));this.K=new _ds.Kk(()=>{rT(this);sT(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.j=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;qT(this);break;case "search-active":tT(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),uT(this,a)}}connectedCallback(){wT(this);xT(this);sT(this);rT(this);this.F.observe(this,{childList:!0,subtree:!0});qT(this);const a=_ds.F();this.authUser=_ds.Zi(_ds.$i(a.href),"authuser")}disconnectedCallback(){_ds.I(this.eventHandler);this.F.disconnect()}C(){return this.j+this.h-this.offset}J(){return this.j+this.h}tb(a){this.updated=!1;if(a){zT(this,a,".devsite-header-upper-tabs");
zT(this,a,".devsite-collapsible-section");zT(this,a,".devsite-product-name-wrapper");zT(this,a,"devsite-language-selector");zT(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&yT(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(yT(c,b),c=_ds.F(),c=_ds.Zi(_ds.$i(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.fh(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.fh(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.bi(this),this.appendChild(a));xT(this);vT(this)}};try{window.customElements.define("devsite-header",AT)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
